### ISSUE TITLE
Question: MPD login failed to Home Assistant (ban IP in the end)

### ISSUE THREAD

**Issue by pickonedev** [MusicPlayerDaemon/MPD#2172]
Hi!

Someone is using MPD integration connecting an external MPD server to Home Assistant?
I have this issue where I get error notification in home assisatnt “Login attempt failed”, after 2-3 more attempts, MPD device is banned…
MPD is installed on a different device than HA, MPD having IP 192.168.0.52 and HA …102

This is what I have as configuration in HA

```
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

I tried adding the ip of MPD to the trusted_proxies, not a solution…
Any idea how to solve it?

Thanks
