### ISSUE TITLE
Add .clang-format for automatically source formatting

### ISSUE THREAD

**Issue by ibmibmibm** [MusicPlayerDaemon/MPD#872]
## Feature request
[Clang-format](https://clang.llvm.org/docs/ClangFormat.html) is a tool to formatting c/c++ code.
Adding this file enabled developer to format all source code to unify format.
I've checked some source code and made one that may fit, any suggestion is welcome!
```
BasedOnStyle: LLVM
AccessModifierOffset: -8
AllowAllConstructorInitializersOnNextLine: false
AlwaysBreakTemplateDeclarations: Yes
BraceWrapping:
  AfterFunction: true
  SplitEmptyFunction: true
BreakConstructorInitializers: BeforeColon
ColumnLimit: 90
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 8
IndentCaseLabels: false
IndentPPDirectives: AfterHash
IndentWidth: 8
Standard: c++17
TabWidth: 8
UseTab: Always
```
